{% set version = "0.4-12" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-kappalab
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/kappalab_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/kappalab/kappalab_{{ version }}.tar.gz
  sha256: b30829a18cc7ee3ee466edbbd6f85e3e41d445887e34eaf6a3fa58f53911138c

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib('c') }}        # [not win]
    - {{ stdlib('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-kernlab
    - r-lpsolve
    - r-quadprog
  run:
    - r-base
    - r-kernlab
    - r-lpsolve
    - r-quadprog

test:
  commands:
    - $R -e "library('kappalab')"           # [not win]
    - "\"%R%\" -e \"library('kappalab')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=kappalab
  license: CECILL-2.0
  license_file: LICENCE
  summary: 'S4 tool box for capacity (or non-additive measure, fuzzy measure) and integral manipulation in a finite setting. It contains routines for handling various types of set functions such as games or capacities. It can be used to compute several non-additive integrals: the Choquet integral, the Sugeno integral, and
    the symmetric and asymmetric Choquet integrals. An analysis of capacities in terms of decision behavior can be performed through the computation of various indices such as the Shapley value, the interaction index, the orness degree, etc. The well-known Möbius transform, as well as other equivalent representations of
    set functions can also be computed. Kappalab further contains seven capacity identification routines: three least squares based approaches, a method based on linear programming, a maximum entropy like method based on variance minimization, a minimum distance approach and an unsupervised approach based on parametric entropies.
    The functions contained in Kappalab can for instance be used in the framework of multicriteria decision making or cooperative game theory.'

extra:
  recipe-maintainers:
    - conda-forge/r
