travis:
  secure:
    BINSTAR_TOKEN: f4QmaGPPHpcqXAX6OlbfacjNzPthABxYt/PblLtcltYUytM2C/yBiUxdnc9U5qTRncdVcEKCTr+mQosDJknchCB4GpqqZvkzJcHhponNXsBayUPKoSrx2CcQ+PsRcPcHQRe4uvhdh/l7DbY2Q8W0ioottGih/AAi4YaQZRIsrXfd7wq2Lp4ObquTruS/rlwYWkqneeoIAR7lbDpTVObWCockQpEVH7euVIAd1ON2P1LRdZfRwJiLar6EUhFVCAnuUffmvR92hoUDNZexzdHHrJzIEQcFeoC3YMZdHlxJ6foKtQ1rTM3I6Ty7s0esn7nzv+iyp7diAxo3wpUwdG7tRAlJj+oG9wFb9F/CfGEsK+jW/fKUlNMuQdhOgG9vf7mm8RaxJ/ZE0h+yaZnH07vKPd72ZN3fXJQLT8ingqWE+VWrGW881kkDE0/fh/4ogzspyHMcJ/cTil4L75AbaId6hZZxlV9QsvJ3CHqcsVH7RnfvBPcsvwQZohBA4+lztWE3Z/LLboUQ8I2GV6PboGpM62gu22uLHgqZQQEttiD6vj7Oua2xXgP70Kqr029rXKcjKzkInt+HZ8KjI89JsdvqPDd65j+0G5Av84+iUXHsYnj9HNzZbRo3WvWh5iAx2qw1+3aIfQOphFnDuye4/Nwts8BpknEl91HpHtfn4SJ8x5U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
